
CREATE TABLE koffeeblog_articles (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    typeid EXT NOT NULL,
    title TEXT NOT NULL,
	imageURL TEXT NOT NULL,
    content TEXT NOT NULL,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);